### ISSUE TITLE
How use this screen(lcd and touch) with raspberry pi zero?

### ISSUE THREAD

**Issue by undermuz** [DustinWatts/Pico-Matrix-Touch-Keyboard#1]
Hello, i have been trying use this screen with raspberry pi zero, but I can't use touchscreen and lcd together, i am using this lib: https://github.com/juj/fbcp-ili9341

Do you known some other libs for this display on raspberry pi zero?

**Comment by DustinWatts** [comment]
I'm using TFT_eSPI in this and many other projects! https://github.com/Bodmer/TFT_eSPI
