### ISSUE TITLE
spi tft display

### ISSUE THREAD

**Issue by tarbear123** [DustinWatts/Pico-Matrix-Touch-Keyboard#2]
i have a spi tft display (with 4 pin connector) how would I create a PCB the use the cable and a pico?

**Comment by tarbear123** [comment]
> Depends on the screen. What screen is it?

it's a nextion display and I was mistaken, it has dupont wires attached to the connector

**Comment by DustinWatts** [comment]
Ow, Nextion requires their drivers. I do not think this is going to work.
